package com.avianca.esb.antifraude.ws_antifraude;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-01T09:02:27.843-06:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "wsAntifraude", 
                  wsdlLocation = "file:/C:/Users/halvarenga/workspace-fuse/ws-antifraude/src/main/resources/wsdl/MAFService.wsdl",
                  targetNamespace = "urn:com.avianca.esb.antifraude:ws-antifraude:1.0") 
public class WsAntifraude extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com.avianca.esb.antifraude:ws-antifraude:1.0", "wsAntifraude");
    public final static QName WsAntifraudePort = new QName("urn:com.avianca.esb.antifraude:ws-antifraude:1.0", "wsAntifraudePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/halvarenga/workspace-fuse/ws-antifraude/src/main/resources/wsdl/MAFService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsAntifraude.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/halvarenga/workspace-fuse/ws-antifraude/src/main/resources/wsdl/MAFService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsAntifraude(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsAntifraude(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAntifraude() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WsAntifraude(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsAntifraude(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsAntifraude(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WsAntifraudePortType
     */
    @WebEndpoint(name = "wsAntifraudePort")
    public WsAntifraudePortType getWsAntifraudePort() {
        return super.getPort(WsAntifraudePort, WsAntifraudePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsAntifraudePortType
     */
    @WebEndpoint(name = "wsAntifraudePort")
    public WsAntifraudePortType getWsAntifraudePort(WebServiceFeature... features) {
        return super.getPort(WsAntifraudePort, WsAntifraudePortType.class, features);
    }

}
