package com.avianca.esb.antifraude.ws_antifraude;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.avianca.esb.antifraude.pojos.AntiFraudEsb;
import com.avianca.esb.antifraude.pojos.ResultadoFraude;

/**
 * This class was generated by Apache CXF 3.1.6 2016-06-01T09:02:27.840-06:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:com.avianca.esb.antifraude:ws-antifraude:1.0", name = "wsAntifraudePortType")
@XmlSeeAlso({ com.avianca.esb.antifraude.pojos.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsAntifraudePortType {

	@WebResult(name = "resultadoFraude", targetNamespace = "urn:com.avianca.esb.antifraude:ws-antifraude:1.0", partName = "return")
	@WebMethod(action = "realizarMAF")
	public ResultadoFraude realizarMAF(
			@WebParam(partName = "arg0", name = "antiFraudEsb", targetNamespace = "urn:com.avianca.esb.antifraude:ws-antifraude:1.0") AntiFraudEsb arg0);
}
